import type { Metadata } from "next";
import { Geist, Geist_Mono, Gelasio } from "next/font/google";
import "./globals.css";
import { Header } from "../components/UI/Navigation/Header";
import Footer from "../components/UI/Navigation/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gelasio = Gelasio({
  variable: "--font-gelasio",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gelasio.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
